### **`NumPy`**  - **designed for fast numerical computing**



- ` NumPy` (short form of Numerical Python) is an open-source Python library used for `numerical computing.`

- It provides tools for working efficiently with `arrays`, `matrices`, and `mathematical functions.` 

- `NumPy` introduces a new data structure called the `ndarray (n-dimensional array),`

- which is much faster and more `memory-efficient` than Python’s built-in lists for numerical operations.
***

*`NumPy is conventionally imported as np to keep code short and readable`*

**`import numpy`**  👉 “Bring NumPy into my program”

**`as np`**  👉 “Give NumPy a short nickname: np”

---

In [43]:
import numpy as np

In [44]:
py_list = [1, 2, 3, 4, 5] 

In [45]:
arr = np.array(py_list)
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


## **`Python Lists VS NumPy Array `**

| Feature                    | Python List                      | NumPy Array (`ndarray`)               |
| -------------------------- | -------------------------------- | ------------------------------------- |
| ***Library***                    | Built-in Python                  | NumPy library                         |
| ***Data Type***                  | Can store mixed data types       | Stores elements of the same data type |
| ***Purpose***                    | General-purpose programming      | Numerical & scientific computing      |
| ***Mathematical Operations***    | No element-wise math             | Supports vectorized operations        |
| ***Example: `* 2`***             | Repeats elements                 | Multiplies each element               |
| ***Speed***                      | Slower                           | Much faster                           |
| ***Memory Usage***               | High (object overhead)           | Low (compact storage)                 |
| ***Internal Storage***           | References to objects            | Continuous memory block               |
| ***Dimensions***                 | 1D only (nested lists are messy) | Supports N-dimensional arrays         |
| ***Shape Awareness***            | No built-in shape                | Has `shape`, `ndim`, `size`           |
| ***Broadcasting***               | Not supported                  | Supported                           |
| ***Used in ML/DL***              | No                             | Yes                                 |
| ***Dependency for Pandas / ML*** | No                             | Yes                                 |
| ***Loop Requirement***           | Needs explicit loops             | No loops (vectorized)                 |
| ***Best Use Case***              | Logic, small programs            | Data analysis, ML, DL                 |

---


### **`Performance Comparison `**




|  🐍 **Python List** 🧍 🧍 🧍 🧍                  | 🔢 **NumPy Array** 🧱 🧱 🧱 🧱                   | 
| -------------------------- | -------------------------------- | 
| Each element is a **separate Python object**      |  All elements have the **same data type**  |
| Elements are stored at **random memory locations** |  Data is stored in **one continuous block of memory** |
| Python performs **type checking at runtime**       |  Operations are executed at **C-level (compiled code)** |
| High **memory and execution overhead**             |  Minimal **runtime overhead** |

---




In [46]:
import time

In [47]:
size = 10_000_000 # large data set of 10 million numbers 

#python list
py_list = list(range(size)) 
start = time.time()
sq_list = [x**2 for x in py_list]   # square of all nums
end = time.time() 
print(f"Python list time = {end-start} seconds.")

Python list time = 0.6565215587615967 seconds.


In [48]:
#numpy arrays
np_array = np.array(py_list) 
start = time.time()
sq_array = np_array ** 2  # vectorized operation
end = time.time() 
print(f"NumPy array time = {end-start} seconds.")

NumPy array time = 0.019728660583496094 seconds.


### **`Memory Usage Comparison`**

In [49]:
import sys

In [50]:
#python list memory
print(f"Python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

# numpy array memory
print(f"NumPy array size = {np_array.nbytes} bytes")

Python list size = 800000560000000 bytes
NumPy array size = 80000000 bytes


### **`Array Vectorization`**

- ***`Array Vectorization` is the ability of NumPy to perform `operations on entire arrays at once` without explicit loops, resulting in faster and cleaner code.***

- #####  **Arithmetic** 

In [51]:
a = np.array([10, 20, 30])

print("array addition: ", a + 5) 
print("array subtraction: ", a - 5) 
print("array multiplication: ", a * 2) 
print("array square: ", a ** 2) 
print("array division: ", a / 5) 

array addition:  [15 25 35]
array subtraction:  [ 5 15 25]
array multiplication:  [20 40 60]
array square:  [100 400 900]
array division:  [2. 4. 6.]


- #####  **Mathematical Function** 

In [52]:
a = np.array([10, 20, 30])
print(f"Square root: {np.sqrt(a)}")
print(f"Log: {np.log(a)}")
print(f"sin: {np.sin(a)}")

Square root: [3.16227766 4.47213595 5.47722558]
Log: [2.30258509 2.99573227 3.40119738]
sin: [-0.54402111  0.91294525 -0.98803162]


- #####  **Comparison** 

In [53]:
b = np.array([2, 3, 4])
print(f"Greater than 2: {b > 2}")
print(f"Smaller than 2: {b < 2}")

Greater than 2: [False  True  True]
Smaller than 2: [False False False]


### **`Creating NumPy Arrays `**

- ####  **From Python list**

In [54]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1) 
print(type(arr1))
print(arr1.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [55]:
arr2 = np.array([1, 2, 3, 4, 5, "Prime"])
print(arr2) 
print(type(arr2))
print(arr2.dtype)

['1' '2' '3' '4' '5' 'Prime']
<class 'numpy.ndarray'>
<U21


- ####  **Using Built-in Functions**

| Function                        | What it does                                              | Example                                                |
| ------------------------------- | --------------------------------------------------------- | ------------------------------------------------------ |
| `np.zeros(n)`                   | Creates an array of zeros                                 | `np.zeros(5)` → `[0. 0. 0. 0. 0.]`                     |
| `np.ones(n)`                    | Creates an array of ones                                  | `np.ones(3)` → `[1. 1. 1.]`                            |
| `np.arange(start, stop, step)`  | Like Python `range`, but returns array                    | `np.arange(0, 10, 2)` → `[0 2 4 6 8]`                  |
| `np.linspace(start, stop, num)` | Creates **num evenly spaced values** between start & stop | `np.linspace(0, 1, 5)` → `[0. 0.25 0.5 0.75 1.]`       |
| `np.eye(n)`                     | Identity matrix                                           | `np.eye(3)` → 3x3 identity matrix                      |
| `np.random.rand(rows, cols)`    | Random numbers between 0 and 1                            | `np.random.rand(2,3)` → 2x3 matrix with random numbers |


In [56]:
# array of zeros
arr1 = np.zeros(5)
print(arr1)

arr2 = np.zeros(5, dtype="int64")
print(arr2)

arr3 = np.zeros((2, 3), dtype="int64")
print(arr3)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[0 0 0]
 [0 0 0]]


In [57]:
# array of ones
arr1 = np.ones(5, dtype="int64")
print(arr1)

arr2 = np.ones((2, 3), dtype="int64")
print(arr2)

[1 1 1 1 1]
[[1 1 1]
 [1 1 1]]


In [58]:
# prefill array with value
arr = np.full((3, 4), 10)
print(arr) 
print(arr.shape)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
(3, 4)


In [59]:
# array with arange values (step size)
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [60]:
# linespace  -> evenly spaced array (number of values)
arr = np.linspace(0, 100, 4)
print(arr)

[  0.          33.33333333  66.66666667 100.        ]


In [61]:
# Identity matrix
arr = np.eye(3, dtype="int64") 
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [62]:
# random -> fake data
# random numbers between 0 and 1
arr1 = np.random.rand(2, 3)
print(arr1)

print()

arr2 = np.random.randint(1, 10, size=(2, 3))
print(arr2)

[[0.50422704 0.35117362 0.76542858]
 [0.24112544 0.00712279 0.59811308]]

[[3 7 1]
 [1 8 7]]


- ####  **Multi-Dimensional arrays**

In [63]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2D)
print(arr2D.ndim)

[[1 2 3]
 [4 5 6]]
2


## **`Array Attributes/ Properties `**

| Attribute      | Meaning                      | Example            |
| -------------- | ---------------------------- | ------------------ |
| `arr.shape`    | Dimensions (rows, cols)      | `(2, 3)`           |
| `arr.ndim`     | Number of axes/dimensions    | `2`                |
| `arr.size`     | Total elements               | `6`                |
| `arr.dtype`    | Data type of elements        | `int64`, `float64` |
| `arr.itemsize` | Size of one element in bytes | `8`                |
| `arr.nbytes`   | Total bytes used             | `48`               |


In [64]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Dimensions: ", arr.shape)
print(f"Number of Dimensions: {arr.ndim}D")
print("Total elements: ", arr.size)
print("Data type: ", arr.dtype)
print("size of one element in bytes: " , arr.itemsize)
print("total bytes : ", arr.nbytes)




Dimensions:  (3, 3)
Number of Dimensions: 2D
Total elements:  9
Data type:  int64
size of one element in bytes:  8
total bytes :  72


- ####  **Converting existing array by type converting into a new array**

In [65]:
float_arr = arr.astype(np.float64)
print(f"Floatarray = {float_arr}")
print(float_arr.dtype)

Floatarray = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64


## **`Operations on NumPy Arrays `**


- ####  **Reshaping**

- reorganizing elements into a new structure without changing values

- changing the shape (dimensions) of an array without changing its data

**`Reshaping Between Dimensions`**

| From    | To       | Example             |
| ------- | -------- | ------------------- |
| 1D → 2D | table    | `(n,) → (r, c)`     |
| 2D → 1D | flatten  | `arr.reshape(-1)`   |
| 2D → 3D | cube     | `(r,c) → (d,r,c)`   |
| 3D → 2D | collapse | `(d,r,c) → (d*r,c)` |




In [86]:
arr_dim = np.array([1, 2, 3, 4, 5, 6, 7, 8]) 

# 1D → 2D |    table  |  (n,) → (r, c)
arr_dim2d = arr_dim.reshape(2, 4)
print(f"arr_dim2d: \n{arr_dim2d}") 
print(f"Dimensions (m x n) : {arr_dim2d.shape}")
print(f"Dimension of numpy array: {arr_dim2d.ndim}D")

# 2D → 3D | cube     | (r,c) → (d,r,c)
arr_dim3d = arr_dim2d.reshape(2, 2, 2)
print(f"\narr_dim3d: \n{arr_dim3d}") 
print(f"Dimensions (m x n) : {arr_dim3d.shape}")
print(f"Dimension of numpy array: {arr_dim3d.ndim}D")


# 3D → 2D  | collapse  | (d,r,c) → (d*r,c)
arr_dim3d_2d = arr_dim.reshape(-1, 2)
print(f"\narr_dim3d_2d: \n{arr_dim3d_2d}") 
print(f"Dimensions (m x n) : {arr_dim3d_2d.shape}")
print(f"Dimension of numpy array: {arr_dim3d_2d.ndim}D")

arr_dim2d: 
[[1 2 3 4]
 [5 6 7 8]]
Dimensions (m x n) : (2, 4)
Dimension of numpy array: 2D

arr_dim3d: 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions (m x n) : (2, 2, 2)
Dimension of numpy array: 3D

arr_dim3d_2d: 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Dimensions (m x n) : (4, 2)
Dimension of numpy array: 2D


In [66]:
# 2D array with dimensions (3, 2)
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr) 
print(f"Dimensions (m x n) : {arr.shape}")
print(f"Dimension of numpy array: {arr.ndim}D")

[[1 2 3]
 [4 5 6]]
Dimensions (m x n) : (2, 3)
Dimension of numpy array: 2D


In [67]:
# Reshaping array
reshaped = arr.reshape(3, 2)
print(reshaped) 
print(f"Dimensions (mxn) : {reshaped.shape}")
print(f"Dimension of numpy array: {reshaped.ndim}D")

[[1 2]
 [3 4]
 [5 6]]
Dimensions (mxn) : (3, 2)
Dimension of numpy array: 2D


In [68]:
flatten = arr.reshape(-1) 
print(flatten)

[1 2 3 4 5 6]


In [69]:
# flatten array (1D)
flattend = arr.flatten() 
print(flattend) 
print(f"Dimensions (mxn) : {flattend.shape}")
print(f"Dimension of numpy array: {flattend.ndim}D")

[1 2 3 4 5 6]
Dimensions (mxn) : (6,)
Dimension of numpy array: 1D


- ####  **Indexing**


In [70]:
# indexing 1D array
arr = np.array([1, 2, 3, 4, 5])
 
print(arr[0])
print(arr[2])
print(arr[4])


1
3
5


In [71]:
# Indexing 2D array
arr2D = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2D[0])
print(arr2D[0][2])
print(arr2D[1][0])

[1 2 3]
3
4


- ####  **Fancy Indexing**

Accessing array elements using integer arrays/lists of indices 
rather than plain slices ( :  )

In [72]:
# fancy indexing 1D array
arr = np.array([1, 2, 3, 4, 5])
idx = [0, 1, 4]
print(arr[idx])

[1 2 5]


In [73]:
# fancy indexing 2D array
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"{arr2D.ndim}D")
print(arr2D[[0, 2], [1, 2]])

2D
[2 9]


In [74]:
# a) Pick specific rows
print("specific rows: ")
print(arr2D[[0, 2]])

# b) Pick specific columns
print("specific colums: ")
print(arr2D[:, [0, 2]])

# c) Pick specific elements
print("specific elements: ")
print(arr2D[[0, 2], [1, 2]])

specific rows: 
[[1 2 3]
 [7 8 9]]
specific colums: 
[[1 3]
 [4 6]
 [7 9]]
specific elements: 
[2 9]


- ####  **Boolean Indexing**

using a Boolean array (      True /   False      ) to select 
elements from another array


In [75]:
# boolean indexing 1D array
a = np.array([10, 23, 30, 45, 50])

print(a[a > 25])
print(a[(a > 20) & (a < 50)])
print(a[a % 2 == 0])

[30 45 50]
[23 30 45]
[10 30 50]


In [76]:
# boolean indexing 2D array
arr2D= np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# a) Condition on whole array
print(f"a) Condition on whole array: ")
print(arr2D[arr2D > 50])

# b) Condition per row / column
print(f"b) Condition per row / column: ")
print(arr2D[arr2D[:, 0] > 30])   #Give me all rows where the first column value is greater than 30


a) Condition on whole array: 
[60 70 80 90]
b) Condition per row / column: 
[[40 50 60]
 [70 80 90]]


- ####  **Slicing**

`Slicing` selects `continuous blocks` of data using `start:stop:step` and `returns` a `view of the array`.

`[start : stop : step]`

- Slicing a list returns a copy but slicing a NumPy array returns a view - for efficiency.

- View is like a shallow copy that shares the same data as the original array, so no 
duplication happens here. 

| Copy    | View                      | 
| -------------- | ---------------------------- | 
|  `Views` are `fast` and `memory-efficient` (no data duplication).  |  `Copies` are `safe` but `slower` and use `more memory`.   | 
 


In [77]:
# Sliced list is a copy
py_list = [1, 2, 3, 4, 5]
copy_list = py_list[1:4] # [2, 3, 4]
copy_list[1] = 33

print(f"Copy List: {copy_list}") 
print(f"Python List: {py_list}")

Copy List: [2, 33, 4]
Python List: [1, 2, 3, 4, 5]


In [78]:
# Sliced Array is a View
np_arr = np.array([1, 2, 3, 4, 5])
view_arr = np_arr[1:4] # [2, 3, 4]
view_arr[1] = 333

print(f"View Array: {view_arr}") 
print(f"np_array: {np_arr}")

View Array: [  2 333   4]
np_array: [  1   2 333   4   5]


In [79]:
# 1D slicing 
arr1d = np.array([1, 2, 3, 4, 5])

print(arr1d[1:5]) # Stop index is NOT included
print(arr1d[:4])
print(arr1d[::-1]) # reversing array

[2 3 4 5]
[1 2 3 4]
[5 4 3 2 1]


**General 2D slicing syntax :**

`arr[row_start:row_stop, col_start:col_stop]`



In [80]:
# 2D array slicing
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]) 

print(arr2d[0:2, 1:3])

[[2 3]
 [5 6]]


In [81]:
# Slice specific rows
print("Slice specific rows: ")
print(arr2d[0:2, :])

#  Slice specific columns
print("Slice specific columns: ")
print(arr2d[: , 1:3])

# Slice a sub-matrix
print("Slice a sub-matrix: ")
print(arr2d[0:2, 1:3])


Slice specific rows: 
[[1 2 3]
 [4 5 6]]
Slice specific columns: 
[[2 3]
 [5 6]
 [8 9]]
Slice a sub-matrix: 
[[2 3]
 [5 6]]


**Copying numpy array**

- In `NumPy`, `slicing returns a view` by default; `.copy()` must be `used` to create an `independent array`.


In [82]:
arr = np.array([10, 20, 30, 40, 50]) 
sub = arr[1:4].copy() 
sub[0] = 99

print("Subarray: ", sub)
print("Array: ", arr)



Subarray:  [99 30 40]
Array:  [10 20 30 40 50]


**General 3D slicing syntax :**

`arr[block_slice, row_slice, col_slice]`

   

In [83]:
arr3D = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
    ]
])

print(arr3D.ndim,"D")
print(arr3D.shape)

3 D
(2, 3, 3)


In [84]:
print(arr3D[1, 0:2, 0:2])

[[10 11]
 [13 14]]
