## **`NumPy Multidimensional Arrays & Axes`**


`Multi-dimensional arrays` in NumPy are the foundation of most scientific and 
machine-learning work. 

A NumPy array can have `any number of dimensions` (1D, 2D, 3D & so on). 

Each dimension is called an `axis`. 

-  1D array has 1 axis (`axis0`). 
-  2D array has 2 axes (`axis0 = rows`, `axis1 = columns`) 
-  3D array has 3 axes (`axis0 = depth/layer`, `axis1 = rows in each layer`, `axis2 = columns in each layer`)

---

#### **`1D Array (Vector)`**

> - A simple list of values.

> - Only one axis exists.

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4]) 

print(f"Number of axes/dimensions: {a.ndim}D") 
print(f"Dimensions (rows, cols): {a.shape}") 
print(f"Total elements: {a.size}")

Number of axes/dimensions: 1D
Dimensions (rows, cols): (4,)
Total elements: 4


#### **`2D Array (Matrix)`**

> - A table (rows × columns)

> - Two axes exits:

| Axis     | Meaning                     |
| -------- | --------------------------- |
| `axis=0` | Down the rows (column-wise) |
| `axis=1` | Across columns (row-wise)   |


In [3]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
]) 

print(f"Number of axes/dimensions: {b.ndim}D") 
print(f"Dimensions (rows, cols): {b.shape}") 
print(f"Total elements: {b.size}")

Number of axes/dimensions: 2D
Dimensions (rows, cols): (2, 3)
Total elements: 6


In [6]:
# Operations on 2D arrays

print(f"Axis=0 (column sum): {b.sum(axis=0)}")  # column sum
print(f"Axis=1 (row sum): {b.sum(axis=1)}") # row sum

Axis=0 (column sum): [5 7 9]
Axis=1 (row sum): [ 6 15]


In [7]:
print(b[0:2, 1:2])

[[2]
 [5]]


#### **`3D Array (Stack of Matrices)`**

> - A collection of 2D arrays

**Shape Format**

`(number of blocks,`

`number of rows,`
 
`number of columns)`

> - Three axes exits: 

| Axis     | Meaning        |
| -------- | -------------- |
| `axis=0` | Across blocks  |
| `axis=1` | Across rows    |
| `axis=2` | Across columns |



In [4]:
c = np.array([
    # Block 0
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    # Block 1
    [
        [7, 8, 9],
        [10, 11, 12]  
    ]
])

print(f"Number of axes/dimensions: {c.ndim}D") 
print(f"Dimensions (rows, cols): {c.shape}") 
print(f"Total elements: {c.size}")

Number of axes/dimensions: 3D
Dimensions (rows, cols): (2, 2, 3)
Total elements: 12


In [15]:
print(c.sum(axis=0)) # sum of corresponding rows across blocks
print(c.sum(axis=1)) # sum of rows inside each block
print(c.sum(axis=2)) # sum of columns inside each row

[[ 8 10 12]
 [14 16 18]]
[[ 5  7  9]
 [17 19 21]]
[[ 6 15]
 [24 33]]


In [8]:
# operations on 3D array
arr3d = np.array([
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    [
        [7, 8],
        [9, 10],
        [11, 12]
    ]
])

print(arr3d.shape)

(2, 3, 2)


In [14]:
print(arr3d[0,1,1])  # block 0, row 1, column 1

#slicing
print("first row from both layers: ")
print(arr3d[:, 0, :])# first row from both layers

print("first col form both layers:") 
print(arr3d[:, :, 0])#first col form both layers

4
first row from both layers: 
[[1 2]
 [7 8]]
first col form both layers:
[[ 1  3  5]
 [ 7  9 11]]
