## **`Vectorization & Broadcasting in NumPy`**

---

#### **Vectorization**

Vectorization means performing `operations on entire arrays at once` without explicit 
Python loops.  

- NumPy uses `C-level implementations` internally → much faster than Python loops. 

- Makes code `shorter, cleaner, and faster`. 

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4, 5]) 

square_arr = arr1 ** 2     # Square all of nums 
print(square_arr) 

arr2 = np.array([6, 7, 8, 9, 10]) 
print(arr1 + arr2)

[ 1  4  9 16 25]
[ 7  9 11 13 15]


---

#### **Broadcasting**

Broadcasting allows NumPy to `perform operations on arrays of different shapes by automatically expanding the smaller one.`

It’s basically scaling arrays without using extra memory. 

- No need to manually reshape arrays. 

- Useful for `combining arrays of different dimensions`. 

**`Broadcasting Rules`**

- Align shapes from the `right to left`.

- Dimensions are compatible if:

            • They are `equal`, OR

            • One of them is `1`

            • `Missing` (smaller array can be “stretched”).

- If not compatible →  error

In [4]:
# 1D array + scalar

arr = np.array([1, 2, 3]) 
print(arr + 10)

[11 12 13]


In [5]:
# 2D + 1D 

arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr1d = np.array([10, 20, 30]) 

print(arr2d + arr1d)

[[11 22 33]
 [14 25 36]]


In [6]:
# 2D + scalar
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2d + 10)

[[11 12 13]
 [14 15 16]]


In [7]:
a = np.array([12, 24, 36, 45, 60, 72]) 
b = np.array(["Pass", "Fails"]) 

res = np.where(a > 35, b[0], b[1])
print(res)

['Fails' 'Fails' 'Pass' 'Pass' 'Pass' 'Pass']


In [8]:
# matrix X vector
m = np.array([
    [1, 2],
    [3, 4]
])

v = [10, 20] 
res = m * v
print(res)

[[10 40]
 [30 80]]
