## **`Useful Mathematical Functions in NumPy`**

NumPy is massive & provides a `wide range of built-in mathematical functions` that 
are highly optimized and can operate `element-wise on arrays`. 

### **`Aggregation Functions`**

- These are functions that `take an array and reduce it to a single value` (or smaller array) 
by combining elements.

1.  `sum()` - returns sum of all elements 
            
2.  `prod()` - returns product of all elements 

3.  `min()`  - returns minimum value 

4.   `max()` - returns maximum value 

5.   `argmin` -  returns index of min value               
 
6.   `argmax()` -  returns index of max value                                            

7.   `mean()` -  returns mean (average) 

8.   `median()`  - returns median              

9.   `std()`   - returns standard deviation 

10.   `var()`  - returns variance 

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

print(f"sum: {np.sum(arr)}")
print(f"product: {np.prod(arr)}")
print(f"minimum value: {np.min(arr)}")
print(f"maximum value: {np.max(arr)}")
print(f"Index of min value: {np.argmin(arr)}")
print(f"Index of max value: {np.argmax(arr)}")
print(f"mean (average): {np.mean(arr)}")
print(f"median: {np.median(arr)}")
print(f"Standard deviation: {np.std(arr)}")
print(f"Variance: {np.var(arr)}")

sum: 15
product: 120
minimum value: 1
maximum value: 5
Index of min value: 0
Index of max value: 4
mean (average): 3.0
median: 3.0
Standard deviation: 1.4142135623730951
Variance: 2.0


### **`Power Functions`**

1. `square()` - returns square of all elements 
 
2. `sqrt()` - returns square root of all elements 

3. `pow(a, b)` - returns ab 

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(f"Square: {np.square(arr)}")
print(f"Square root: {np.sqrt(arr)}")
print(f"Power: {np.pow(arr, 3)}")

Square: [ 1  4  9 16 25]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Power: [  1   8  27  64 125]


### **`Log & Exponential Functions`**

1. `log()`   - returns natural log 

2. `log10()` - returns log base 10

3. `log2()`  - returns log base 2 

4. `exp(x)` - returns e^x 


In [5]:
print(np.log(arr))  
print(np.log10(arr))  
print(np.log2(arr))  
print(np.exp(arr)) 

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### **`Rounding Functions`**

1. `round()`  - rounds off to nearest value

2. `ceil()`  - rounds up 

3. `floor()` - rounds down  

4. `trunc(x)` - truncates(removes) the fractional part    

In [6]:
print(np.round(2.678)) # 3.0  
print(np.floor(2.678)) # 2.0 
print(np.ceil(2.678))  # 3.0  
print(np.trunc(2.678)) # 2.0 

3.0
2.0
3.0
2.0


### **`Miscellaneous Functions`**

1. `abs()` - returns absolute value 

2. `sort()` - returns sorted (arranges in increasing order) values

3. `unique()` - returns unique values    




In [7]:
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5]) 

print(np.abs(arr))  

print(np.sort(arr))  

print(np.unique(arr))  


[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]
